# Generated by Django 5.0.1 on 2024-03-21 17:34

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoCom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_contacto', models.CharField(max_length=100)),
                ('tipo_trabajo', models.CharField(max_length=100)),
                ('descripcion_trabajo', models.TextField(blank=True)),
                ('fecha_contacto', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
            ],
        ),
    ]
