# Generated by Django 4.2.11 on 2024-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoCom', '0004_servicios_alter_contacto_fecha_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imagen_trabajo',
            field=models.ImageField(null=True, upload_to='fotoservicios'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
