# Generated by Django 4.2.11 on 2024-04-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoCom', '0006_contacto_estado_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='estado_trabajo',
            field=models.BooleanField(default=True),
        ),
    ]
